type: object
properties:
  coffee_machine_runtime_state:
    required: true
    type: integer
    description: |
      Setzt den aktuellen Runtime Status der Kaffeemaschine.
      1 = Kaffeemaschine anschalten
      2 = Kaffeemaschine ausschalten 
    example: 2