#%RAML 1.0
title: IoT Coffee Machine
version: v1.0
protocols: [ HTTP, HTTPS ]
mediaType:  application/json

securitySchemes:
  jwt: !include securitySchemes/custom-jwt.raml

types:
  device-settings: !include types/device-settings.raml
  device-status: !include types/device-status.raml
  device-status-edit: !include types/device-status-edit.raml
  device-job: !include types/device-job.raml
  device-job-create: !include types/device-job-create.raml

/api/device:
  /settings:
    securedBy: [ jwt ]
    get:
      description: Liefert die aktuellen Einstellungen der Kaffeemaschine.
      responses: 
        200:
          description: Ok.
          body:
            type: device-settings
    put:
      description: Ändert die aktuellen Einstellungen der Kaffeemaschine
      body:
        type: device-settings
      responses: 
        200:
          description: Ok. Einstellungen der Kaffeemaschine geändert.
  /job:
    securedBy: [ jwt ]
    post:
      description: Führt einen Auftrag auf der Kaffeemaschine aus.
      body:
        type: device-job-create
      responses:
        201:
          description: Created.
          body:
            type: device-job
  /status:
    securedBy: [ jwt ]
    get:
      description: Liefert den aktuellen Status der Kaffeemaschine.
      responses: 
        200:
          description: Ok.
          body:
            type: device-status
    put:
      description: Setzt die veränderbaren Status der Kaffeemaschine.
      body:
        type: device-status-edit
      responses: 
        200:
          description: Ok.
          body:
            type: device-status

